apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-with-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-with-k8s
  template:
    metadata:
      labels:
        app: rest-server
    spec:
      containers:
        - name: rest-server
          image: julppu/rest-with-devops:1.05
